### ISSUE TITLE
Add image display (like in getpocket.com list) to generated list

### ISSUE THREAD

**Issue by mylesagray** [ciaranmahoney/pocket-wp#2]
If possible can an image be added to the generated list (the same way getpocket.com has) as this info can be pulled from the API:

http://getpocket.com/developer/docs/v3/retrieve

has_image - 0, 1, or 2 - 1 if the item has images in it - 2 if the item is an image
images - A JSON object listing all of the images associated with the item

Example response (JSON):
HTTP/1.1 200 OK
Content-Type: application/json
Status: 200 OK

{"status":1,"list":{"229279689":{"item_id":"229279689",
"resolved_id":"229279689",
"given_url":"http:\/\/www.grantland.com\/blog\/the-triangle\/post\/_\/id\/38347\/ryder-cup-preview",
"given_title":"The Massive Ryder Cup Preview - The Triangle Blog - Grantland",
"favorite":"0",
"status":"0",
"resolved_title":"The Massive Ryder Cup Preview",
"resolved_url":"http:\/\/www.grantland.com\/blog\/the-triangle\/post\/_\/id\/38347\/ryder-cup-preview",
"excerpt":"The list of things I love about the Ryder Cup is so long that it could fill a (tedious) novel, and golf fans can probably guess most of them.",
"is_article":"1",
"has_video":"1",
"has_image":"1",
"word_count":"3197",
"images":{"1":{"item_id":"229279689","image_id":"1",
    "src":"http:\/\/a.espncdn.com\/combiner\/i?img=\/photo\/2012\/0927\/grant_g_ryder_cr_640.jpg&w=640&h=360",
    "width":"0","height":"0","credit":"Jamie Squire\/Getty Images","caption":""}},
"videos":{"1":{"item_id":"229279689","video_id":"1",
    "src":"http:\/\/www.youtube.com\/v\/Er34PbFkVGk?version=3&hl=en_US&rel=0",
    "width":"420","height":"315","type":"1","vid":"Er34PbFkVGk"}}}}}

**Comment by ciaranmahoney** [comment]
Hi Myles,

Good suggestion. I will do my best to add this feature sometime this week. 

Thanks!

**Comment by ciaranmahoney** [comment]
Ok, this is done. I added another shortcode parameter - image (yes or no) - it shows no image by default. At this stage it only works for links that return 1 for has_image. I was getting some errors with 2 (when link is actually an image) and I don't have any more time to figure it out for now. If there is no image on a link, there is a placeholder grey box, like the screenshot below. 

I don't have time to do a proper release to the WP repo right now, but feel free to test and let me know if it works for. I'll try to a proper version/readme update and upload to WP repo tomorrow. 

![screenshot 2015-03-12 16 22 54](https://cloud.githubusercontent.com/assets/955303/6630284/5ba63680-c8d4-11e4-9bf7-5c936cbad678.png)

**Comment by mylesagray** [comment]
Okay great Ciaran, I'll test it out and fiddle with the code a bit, set up a pull request if I come up with anything.
