### ISSUE TITLE
Add trigger to shortcode for "status" API element

### ISSUE THREAD

**Issue by mylesagray** [ciaranmahoney/pocket-wp#3]
To display either archived or deleted items (mainly function is wanted for archived (read) items).

http://getpocket.com/developer/docs/v3/retrieve

status - 0, 1, 2 - 1 if the item is archived - 2 if the item should be deleted

**Comment by ciaranmahoney** [comment]
Ok, have got this sorted. Will push an update soon.

**Comment by ciaranmahoney** [comment]
I've pushed the commits for this issue. I haven't updated in the official WP repo yet as I am going to add the image feature now. Will update in WP repo once I've done that. Cheers
